version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://quantumnet:${POSTGRES_PASSWORD}@db:5432/quantumnet
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
    networks:
      - quantumnet-network

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=quantumnet
      - POSTGRES_USER=quantumnet
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - quantumnet-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - quantumnet-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - quantumnet-network

volumes:
  postgres_data:
  redis_data:

networks:
  quantumnet-network:
    driver: bridge